config/routes.rb
BackMonkey::Application.routes.draw do

  root :to => 'pages#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post '/alcoholcalc/create.json', to: 'alcohol_calc#create', :as => 'alcohol_calc'
  post '/caffeinecalc/create.json', to: 'caffeine_calc#create', :as => 'caffeine_calc'
  post '/nicotine/create.json', to: 'nicotine_calc#create', :as => 'nicotine_calc'

end

app/views/chart/_bac_form.html.haml
#bac_form.substance_form
  = form_for :alcohol_calc, url: alcohol_calc_path, remote: true do |f|
    .line.first
      I am a
      = f.select :gender, options_for_select([["Male", 'm'],["Female",'f']], @gender), {required: true}, { :class => "drop_down" }
      weighing
      = f.number_field :weight, required: true, min: 0, value: @weight
      pounds.

    .line
      I had
      = f.number_field :drinks, required: true
      drinks over
      = f.number_field :hours, required: true, min: 0
      hours.

      = render "chart/save_option"
    .submit
      = f.submit "Calculate BAC", :class=> "button", :id=> "alc_button"

app/views/chart/_caffeine_form.html.haml
#caffeine_form.substance_form.hidden
  = form_for :caffeine_calc, url: caffeine_calc_path, remote: true do |f|
    .line
      I had
      = f.number_field :cups, required: true, min: 1
      cups of
      = f.select :type, options_for_select([['coffee', 'coffee'],['tea', 'tea']]), {required: true}, {:class => "drop_down"}
      in
      = f.number_field :hours, required: true, min: 1
      hours.
      = render "chart/save_option"
    .submit
      = f.submit "Check caffeine levels", :class=> "button", :id=>"caf_button"

app/views/chart/_chart_warning.html.haml
.drive.hidden.bac-limit
  %p You are legally intoxicated. Don't drive!

.dead.hidden.bac-limit
  %p You are lethally intoxicated.

app/views/chart/_nicotine_form.html.haml
#nicotine_form.substance_form.hidden
  = form_for :nicotine_calc, url: nicotine_calc_path, remote: true do |f|
    .line
      I had
      = f.number_field :cigarettes, required: true, min: 1
      cigarettes
      in
      = f.number_field :hours, required: true, min: 1
      hours.
      = render "chart/save_option"
    .submit
      = f.submit "Check nicotine levels", :class=> "button", :id=> "nic_button"

app/views/chart/_s_bac_form.html.haml
#s_bac_form.mobile.substance_form
  = form_for :alcohol_calc, url: alcohol_calc_path, remote: true do |f|
    .line
      = f.select :gender, options_for_select([["Male", 'm'],["Female",'f']], @gender), {required: true}, { :class => "drop_down" }
    .line
      = f.label :weight
      = f.number_field :weight, required: true, min: 0, value: @weight
    .line
      = f.label :drinks
      = f.number_field :drinks, required: true, min: 1
    .line
      = f.label :hours
      = f.number_field :hours, required: true, min: 1
    = render "chart/save_option"
    .submit
      = f.submit "Calculate BAC", :class=> "button", :id=> "alc_button"

app/views/chart/_s_caffeine_form.html.haml
#s_caffeine_form.mobile.substance_form.hidden
  = form_for :caffeine_calc, url: caffeine_calc_path, remote: true do |f|
    .line
      = f.select :type, options_for_select([['coffee', 'coffee'],['tea', 'tea']]), {required: true}, {:class => "drop_down"}
    .line
      = f.label :cup
      = f.number_field :cups, required: true, min: 1
    .line
      = f.label :hours
      = f.number_field :hours, required: true, min: 1
    = render "chart/save_option"
    .submit
      = f.submit "Check caffeine levels", :class=> "button", :id=>"caf_button"

app/views/chart/_s_nicotine_form.html.haml
#s_nicotine_form.mobile.substance_form.hidden
  = form_for :nicotine_calc, url: nicotine_calc_path, remote: true do |f|
    .line
      = f.label :cigarettes
      = f.number_field :cigarettes, required: true, min: 1
    .line
      = f.label :hours
      = f.number_field :hours, required: true, min: 1
    = render "chart/save_option"
    .submit
      = f.submit "Check nicotine levels", :class=> "button", :id=> "nic_button"

app/views/chart/_save_option.html.haml
#save_option
  - if current_user
    = check_box_tag 'save_search', true, true
    Save this search