config/routes.rb
BackMonkey::Application.routes.draw do

  root :to => 'pages#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post '/alcoholcalc/create.json', to: 'alcohol_calc#create', :as => 'alcohol_calc'
  post '/caffeinecalc/create.json', to: 'caffeine_calc#create', :as => 'caffeine_calc'
  post '/nicotine/create.json', to: 'nicotine_calc#create', :as => 'nicotine_calc'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :email, :password, :gender, :weight
  has_many :consumption_records
  validates :user_name, :email, :gender, :weight, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :gender, inclusion: { in: ["m", "f"]}
  validates :user_name, :email, uniqueness: true
  has_secure_password

  def daily_average_alcohol
    self.total_alcohol / days_account_open
  end

  def daily_average_caffeine
    self.total_caffeine / days_account_open
  end

  def daily_average_nicotine
    self.total_nicotine / days_account_open
  end

  def past_month_consumption
    self.consumption_records.where('created_at > ?', (Time.zone.now - 18141000)).reverse
  end

  def past_week_consumption
    self.consumption_records.where('created_at > ?', (Time.zone.now - 604800)).reverse
  end

  def days_account_open
    days = ((Time.zone.now - self.created_at)/86400).ceil
    days == 0 ? 1 : days
  end

  def daily_comparison_alcohol
    (((self.daily_average_alcohol - 0.6) / 0.6) * 100).floor
  end

  def daily_comparison_caffeine
    (((self.daily_average_caffeine - 300) / 300.0) * 100).floor
  end

  def daily_comparison_nicotine
    (((self.daily_average_nicotine - 15) / 15.0) * 100).floor
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_authentication, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    if user.save
      login(user)
      redirect_to root_path
    else
      redirect_to new_user_path, notice: "That username or email address is already registered."
    end
  end

  def show
    @history = current_user.past_week_consumption
  end

end

app/views/users/_comparisons.html.haml
#comparisons
  %h3 How you compare
  .substance_comparisons
    - if current_user.daily_comparison_alcohol > 0
      %span.green_num= current_user.daily_comparison_alcohol
    - else
      %span.red_num= current_user.daily_comparison_alcohol
      %p than the average user
    = image_tag "beer.png"
  .substance_comparisons{class: "middle"}
    - if current_user.daily_comparison_caffeine > 0
      %span.green_num= current_user.daily_comparison_caffeine
    - else
      %span.red_num= current_user.daily_comparison_caffeine
      %p than the average user
      = image_tag "coffee.png"
  .substance_comparisons
    - if current_user.daily_comparison_nicotine > 0
      %span.green_num= current_user.daily_comparison_nicotine
    - else
      %span.red_num= current_user.daily_comparison_nicotine
      %p than the average user
    = image_tag "cigg.png"

app/views/users/_consumption_hist.html.haml
#consumption_history
  %h3 Drugs this week
  - if @history.empty?
    %p.gray None yet!
  - @history.each do |consumption_record|
    %p
      = consumption_record.dose_description
      %span.date= consumption_record.created_at.strftime("%m/%d/%y")

app/views/users/_daily_alc.html.haml
.consumption_summary
  .user_info
    #alc_daily.daily_info
      %span.big_num= current_user.daily_average_alcohol
      %p drinks per day
    .total_info
      %span.big_num= current_user.total_alcohol
      %p drinks total
  .tips
    %h3
      Alcohol (C
      %sub>2
      H
      %sub>5
      OH)
    %p Ethyl alcohol is a depressant intoxicant and one of the most commonly used drugs in the world. In large quantities alcohol reduces inhibition, impairs judgement, and dulls pain. Excess consumption can lead to liver damage and other serious health problems.
    .advice
      %p
        %span.average_num 0.6 drinks per day is the American average.
      %p
        %span.average_num 2.0 drinks per day is the recommended maximum.

app/views/users/_daily_caff.html.haml
.consumption_summary
  .user_info
    #caff_daily.daily_info
      %span.big_num= current_user.daily_average_caffeine
      %p mgs caffeine per day
    .total_info
      %span.big_num= current_user.total_caffeine
      %p mgs caffeine total
  .tips
    %h3
      Caffeine (C
      %sub>8
      H
      %sub>10
      N
      %sub>4
      O
      %sub>2)
    %p Caffeine is a crystalline xanthine alkaloid and a stimulant drug. Caffeine is commonly consumed to decrease fatigue and increase alertness. Excess consumption can lead to caffeine addiction, increased blood pressure, sleep disruption.
    .advice
      %p
        %span.average_num 300 mgs per day is the American average.
      %p
        %span.average_num 600 mgs per day is the recommended maximum.

app/views/users/_daily_nic.html.haml
.consumption_summary
  .user_info
    #nic_daily.daily_info
      %span.big_num= current_user.daily_average_nicotine
      %p mgs nicotine per day
    .total_info
      %span.big_num= current_user.total_nicotine
      %p mgs nicotine total
  .tips
    %h3
      Nicotine (C
      %sub>10
      H
      %sub>14
      N
      %sub>2
      )
    %p Nicotine is a parasympathomimetic alkaloid and a stimulant drug. Excess consumption can lead to anxiety and sleep disruption. Regularly smoking tobacco greatly increases the risk of some cancers and emphysema.
    .advice
      %p
        %span.average_num 15 mgs per day is the American average.
      %p
        %span.average_num 0 mgs per day is the recommended maximum.

app/views/users/_s_new.html.haml
#mobile_registration.registration_form
  = form_for @user do |f|
    = f.label "Username"
    = f.text_field :user_name
    = f.label :email
    = f.text_field :email
    = f.label :password
    = f.password_field :password
    = f.label :weight
    = f.number_field :weight, min: 1
    = f.select :gender, options_for_select([["Male", 'm'],["Female",'f']]),{required: true}, { :class => "drop_down" }
    = f.submit "Sign Up", :class=> "button"

app/views/users/_sign_in_error.html.haml
#login_fail
  %p.error= "Invalid username or password"

app/views/users/_sign_in_form.html.haml
.signin_form.hidden
  = form_for :user, url: sessions_path, remote: true do |f|
    = f.text_field :user_name, placeholder: 'Enter your username or email'
    = f.password_field :password, placeholder: 'Password'
    = f.submit "Sign In", :class=> "button", id: "login"
    .error_container

app/views/users/new.html.haml
#signup_message
  - if flash[:notice]
    %p.error= flash[:notice]
  - else
    %span.pop Sign up to start tracking your bad habits
    %p BAC monkey will record your consumption habits when you're signed in. Find out your daily averages and how you compare to other users.

#desktop_registration.registration_form
  = form_for @user do |f|
    = f.label "Username"
    = f.text_field :user_name, required: true
    = f.label :email
    = f.email_field :email, required: true
    = f.label :password
    = f.password_field :password, required: true
    = f.label :weight
    = f.number_field :weight, min: 1, required: true
    = f.label :gender
    = f.select :gender, options_for_select([["Male", 'm'],["Female",'f']]), {required: true}, { :class => "drop_down" }
    = f.submit "Sign Up", :class=> "button"
= render "s_new"

app/views/users/show.html.haml
#user_profile
  = render partial: "daily_alc"
  = render partial: "daily_caff"
  = render partial: "daily_nic"
  = render partial: "consumption_hist"
  = render partial: "comparisons"