config/routes.rb
BackMonkey::Application.routes.draw do

  root :to => 'pages#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post '/alcoholcalc/create.json', to: 'alcohol_calc#create', :as => 'alcohol_calc'
  post '/caffeinecalc/create.json', to: 'caffeine_calc#create', :as => 'caffeine_calc'
  post '/nicotine/create.json', to: 'nicotine_calc#create', :as => 'nicotine_calc'

end

app/views/pages/_desktop_forms.html.haml
#desktop_forms
  = render "chart/caffeine_form"
  = render "chart/bac_form"
  = render "chart/nicotine_form"

app/views/pages/_desktop_links.html.haml
#desktop_links
  = link_to 'Alcohol', '#', :id => 'bac'
  = link_to 'Caffeine', '#', :id => 'caffeine'
  = link_to 'Nicotine', '#', :id => 'nicotine'

app/views/pages/_footer.html.haml
#footer
  #up.arrow.hidden
    %h5 show
  #down.arrow
    %h5 hide
  #lower_nav
    = render "desktop_links"
    = render "mobile_links"
  #form_container
    = render "desktop_forms"
    = render "mobile_forms"

app/views/pages/_mobile_forms.html.haml
#mobile_forms.hidden
  = render "chart/s_caffeine_form"
  = render "chart/s_bac_form"
  = render "chart/s_nicotine_form"

app/views/pages/_mobile_links.html.haml
#mobile_links
  = link_to 'Alcohol', '#', :id => 's_bac'
  = link_to 'Caffeine', '#', :id => 's_caffeine'
  = link_to 'Nicotine', '#', :id => 's_nicotine'

app/views/pages/_nav_topbar.html.haml
%nav#topbar
  = link_to image_tag("smoking_monkey.jpg", :alt => "monkey_logo"), root_path
  %h3 BAC Monkey
  - if current_user && !current_page?(root_path)
    = link_to "Home", root_path, id:"home-button"
    = link_to "Sign Out", session_path(current_user), method: 'DELETE', id:"signout"
  - elsif current_user
    = link_to "Profile", user_path(current_user), id:"profile-button"
    = link_to "Sign Out", session_path(current_user), method: 'DELETE', id:"signout"
  - else
    = link_to "Sign Up", new_user_path, id:"signup"
    = link_to "Sign In", '#', id:"signin", remote: true

app/views/pages/index.html.haml
#welcome_msg
  #blurb
    %span.pop BAC Monkey is a personal tracker for your chemical vices.

    %p Fill out the form below to start tracking your blood alcohol content (BAC). It will graph your estimated BAC over time, so you can decide whether you've had one beer too many (or too few).

#svg-container
  = render 'chart/chart_warning'

= render "footer"